### ISSUE TITLE
Handle situation when external API is down

### ISSUE THREAD

**Issue by chrzrdx** [kvsrinivas91/edyst-s19-diy-pokedex#3]
What happens when the external API goes down? Your API will be unable to serve requests as well.

You can store a local copy of that data (scrape it from the external API once, and if it's down, you can return the pokemon data from this local copy instead)

**Comment by kvsrinivas91** [comment]
Situation handled.
I extracted all the pokemon data required and saved it in json file.
Now the program can work without PokeApi.
