### ISSUE TITLE
You're still using the external API without a fallback

### ISSUE THREAD

**Issue by chrzrdx** [kvsrinivas91/edyst-s19-diy-pokedex#4]
https://github.com/kvsrinivas91/edyst-s19-diy-pokedex/blob/fdbc2c407ca86dc5c3df5402112164be4a44972d/backend/app.py#L10

Turn off your internet connection, and try to run your api - in this case, your API should give answers from the local data you've collected

**Comment by kvsrinivas91** [comment]
My mistake sir, Iaccidentally lost the code. So I reuploaded the correct code.
Now the program runs without the internet
