### ISSUE TITLE
BONUS: Auto update local data

### ISSUE THREAD

**Issue by chrzrdx** [kvsrinivas91/edyst-s19-diy-pokedex#5]
Explore ways to keep the local copy of data updated with the external API (update once every 12 hours or so).

@harsh20599 thoughts?

**Comment by kvsrinivas91** [comment]
I will try doing it sir, I will try setting a timer and update it every 12 hours

**Comment by kvsrinivas91** [comment]
Yes sir, found a way to do it.
It can be done using windows task scheduler.
